#!/bin/sh


while [ 1 ]; do
    # check pytrans
    pytrans_pid=`ps -ef | grep -v "grep" | grep "pytrans.py" | awk 'BEGIN {FS=" "}; {print $2}'`
    if [ -z "${pytrans_pid}" ]
    then
        /home/moxa/pytrans/pytrans.py &>/dev/null &
    fi
    
    sleep 60
done
